Pagina codigo de conducta agregada y componente suscribe agregado al Layout
javascriptecuador/web pull request #50
Opened 2020-10-15 20:29 UTC by jordanrjcode

**Descripción del cambio**: Pagina codigo de conducta lista para ser visitada tambien agregue el componente suscribe al layout principal 

**Razón del cambio**: Agregue el componente suscribe al layout para que se pueda visualizar en todas las paginas tal como lo muestra el prototipo de figma y finalice la pagina codigo de conducta y esta redireccionando correctamente desde el navbar

**Captura**:
 ![Imagen -capture codigode conducta](https://lh3.googleusercontent.com/6GQu2JioSs3_-srqmUkF8raHSg-a5Yv3kOp1Xrr8xZ0pJ-rCNn392176pfZLF9fyE0Ba=s151)

**Otros cambios**: No se hicieron mas cambios

**Link al origen de este PR**:

Closes #
#42

2020-10-15 21:12 UTC, rpalaciosg requested changes
Actualizar su repositorio con los ultimos cambios en produccion, y corregir los conflictos que se dan por el archivo `home.js` el cual ya no existe.

2020-10-15 21:12 UTC, rpalaciosg commented on src/pages/home.js
>  import CiudadesSection from "../components/ciudades-section/ciudades-section";
Este archivo `home.js`  se elimino para mejorar la estructura del proyecto, era repetitivo tener un index.js y un home.js.
Se deberia hacer un `git pull upstream master` luego hacer un merge de los cambios descargados con los aplicados en su pull request, para evitar conflictos.

2020-10-16 04:29 UTC, israteneda requested changes

2020-10-16 04:29 UTC, israteneda commented on src/pages/code-of-conduct.js
> +      <img className="mx-auto my-5" src="/static/codeconduct.svg" />
La imagen codeconduct al parecer no está en el proyecto, por lo que no se está mostrando en la página

![image](https://user-images.githubusercontent.com/20668624/96213203-0a4adf00-0f3e-11eb-931a-81d531e6cf8c.png)

2020-10-16 04:29 UTC, israteneda commented on src/components/layout/layout.js
> +import Suscribe from "../suscribe/suscribe";
Aquí esta la razón del problema, debería ir `subscribe` en vez de `suscribe`:
```
import Suscribe from "../subscribe/subscribe";
```

2020-10-16 04:34 UTC, israteneda commented on src/pages/code-of-conduct.js
> +      <img className="mx-auto my-5" src="/static/codeconduct.svg" />
Podrías exportarla desde el prototipo:

![image](https://user-images.githubusercontent.com/20668624/96213566-f2c02600-0f3e-11eb-8bfe-1012c8c28101.png)

2020-10-16 04:55 UTC, jordanrjdev commented on src/pages/code-of-conduct.js
> +      <img className="mx-auto my-5" src="/static/codeconduct.svg" />
La exporte incluso la puse en static como svg

2020-10-21 00:38 UTC, cesardlinx requested changes
@jordanrjcode yo te sugeriria que actualices tu repositorio local primero y luego hagas los cambios pertinentes tal como lo dijo @rpalaciosg y de ahi si los envias.

2020-10-21 00:38 UTC, cesardlinx commented on src/pages/code-of-conduct.js
> +const CodeOfConduct = () => {
```suggestion
import codeConductImg from '../images/codeconduct.svg'

const CodeOfConduct = () => {
```

Aqui la imagen deberia estar en la carpeta images y deberias importarla de esta manera

2020-10-21 00:38 UTC, cesardlinx commented on src/pages/code-of-conduct.js
> +      <img className="mx-auto my-5" src="/static/codeconduct.svg" />
```suggestion
      <img className="mx-auto my-5" src={codeConductImg} />
```
Si haces la importación como te la pongo arriba aqui simplemente la usas asi

2020-10-21 16:23 UTC, israteneda approved these changes

2020-10-22 03:43 UTC, merged