Arregla issue 2 - Crear componente Navbar
javascriptecuador/web pull request #60
Opened 2020-10-22 19:13 UTC by rpalaciosg

**Descripción del cambio**:
Modificacion de estilos del Navbar dentro del componente `header.js`

**Razón del cambio**:
Dejar estilos acorde al prototipo.

**Captura**:

![navbar](https://user-images.githubusercontent.com/11642622/96918922-a1e58b80-1470-11eb-8f7a-a39b2b2809a4.gif)

**Otros cambios**:
Se crean las paginas faltantes en blanco para el funcionamiento del navbar:
- eventos
- ciudades
- cuentas

**Link al origen de este PR**:

Closes #2

2020-10-22 19:45 UTC, israteneda commented
Chamo al parecer esta dando un problema al hacer build del proyecto lo podrías revisar https://app.netlify.com/sites/academiatemple/deploys/5f911f9ce2b5cb00085ea2bc

2020-10-22 19:54 UTC, israteneda requested changes

2020-10-22 19:54 UTC, israteneda commented on src/components/header/header.js
> +import escudo from "../../images/Logo-escudo-ec.svg";
Al parecer aquí está dando un problema en el build porque me parece que el logo es con minúscula

2020-10-22 20:20 UTC, rpalaciosg commented on src/components/header/header.js
> +import escudo from "../../images/Logo-escudo-ec.svg";
Acabo de hacer el commit corrigiendo eso.

2020-10-23 15:08 UTC, israteneda requested changes

2020-10-23 15:08 UTC, israteneda commented on package.json
> +    "styled-components": "^5.2.0",
Al parecer faltan otras dependencias según la [documentación en Gatsby](https://www.gatsbyjs.com/docs/styled-components/) para que funcione styled components:
```
npm install gatsby-plugin-styled-components styled-components babel-plugin-styled-components
```

2020-10-23 15:08 UTC, israteneda commented on package.json
> +    "styled-components": "^5.2.0",
También hay que agregar esta línea en el archivo `gatsby-config.js` según la [documentación](https://www.gatsbyjs.com/docs/styled-components/):
```
module.exports = {
  plugins: [`gatsby-plugin-styled-components`],
}
```

2020-10-23 15:13 UTC, israteneda commented on package.json
> +    "styled-components": "^5.2.0",
Pueda que por eso no se este realizando el [build correctamente](https://app.netlify.com/sites/javascriptecuador/deploys/5f91e94bde370b00086a5419)

2020-10-23 16:07 UTC, rpalaciosg commented on package.json
> +    "styled-components": "^5.2.0",
mm esta raro, voy agregar esas libs.

2020-10-23 16:42 UTC, rpalaciosg commented on package.json
> +    "styled-components": "^5.2.0",
Listo instale las librerias, acabo de hacer push del commit. que lo arregla.

2020-10-23 20:47 UTC, israteneda approved these changes

2020-10-23 20:47 UTC, merged